defaults:
  - backbone: wan22
  - lora: video_dit
  - _self_

_target_: runtime.create_easywam_unified
attention_backend: ${model.backbone.attention_backend}
action_dim: ${data.train.processor.action_output_dim}
state_dim: ${data.train.processor.proprio_output_dim}
state_position: sequence
projector_hidden_dim: 64
skip_dit_load_from_pretrain: false

video_scheduler: ${model.backbone.video_scheduler}

loss:
  lambda_video: 1.0
  lambda_action: 1.0
